### ISSUE TITLE
Requesting a demo dataframe format.

### ISSUE THREAD

**Issue by Valentin-Bio** [James-S-Santangelo/glue_pc#1]
Hello James! thanks for this awesome work and for sharing the repository. 

Currently I'm trying to replicate one of the figures of your paper which consist in explaining the variations in the slope of HCN clines (figure 4.A of your paper). For this purpose, I'm following the instructions in your main.R file but given the dependency of the python scripts and my skill issue to run those scripts, I would be grateful if you can give me the format of the dataframe that is stored in the 'outpath' directory that is present in the appended image so I can make a synthetic dataframe to follow the next steps in the main.R file. 

![image](https://github.com/user-attachments/assets/166ae166-53c0-4e57-805d-611d12c26303)

(the image screenshot is part of the  CleanEnviroData.R file )

I'm just interested in the way the figure 4.A is produced so I can make a similar plot with my data :)

best regards and thanks in advance,

Valentín.

**Comment by James-S-Santangelo** [comment]
Hey Valentín,

To generate Figure 4, you need a dataframe that looks something like the attached `model_matrix.csv`. In our case, this dataframe included the Log Odds (i.e., betaLog) change in HCN frequency across the urbanization gradients for each of 160 cities (rows in our dataframe). These were extracted from the random effects of a linear mixed-effects model predicting the change in the probability that a plant is cyanogenic from urban to rural populations and essentially summarizes the effect of urbanization on HCN frequencies across our cities. 

We were interested in seeing what predicts variation in these Log Odds (i.e., strength of clines) across cities, so the remaining columns in our dataframe are standardized environmental variables extracted for each city. These are either Means (i.e., mean standardized environmental variable across all populations within a city), or Slopes (i.e., Change in standardized environmental values along the urbanization gradient for a city). The latter were generated by extracting the beta coefficient from a Robust Linear Regression model with the environmental variable as the response, and distance to the city center as the predictor for a given city. 

From this dataframe, we determined which environmental predictors (or combinations thereof) predict the variation in Log Odds across cities. Once we identified the most important ones (using Elastic Net Regression in out case), we plotted them in figure 4 with the help f the `emmeans` package (see `main_text_figures.R` script). If you can generate a dataframe that looks like the attached `model_matrix.csv` file, you should have no problem regenerating a version of Figure 4 for your data. 

Hope this helps, but feel free to reach out with any other questions!

James

[model_matrix.csv](https://github.com/user-attachments/files/16575909/model_matrix.csv)

**Comment by Valentin-Bio** [comment]
Thanks so much  Dr for your detailed response! it helped me a lot in getting the plot. 

bests,

Valentín.

**Comment by James-S-Santangelo** [comment]
No problem, glad it helped!
